# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy", "pandas"]
# ///
"""
Initial-state (post-consolidation, before cyclic loading) decomposition of
the contact-normal force into the local cylindrical frame for the
expanded simulation set (2 D_r x 5 K_0).

For each ball-ball contact, the unit normal is rotated to the local
(theta, r, z) frame.  The applied torsion tau_{z theta} is carried by
the projection of the contact normal onto the (z, theta) plane;
purely radial contacts are mechanically inert.  Per contact:

    s_c = sqrt(n_z^2 + n_theta^2)             (geometric participation, in [0,1])
    f_n^c s_c                                  (normal force in (z,theta) plane, N)

Specimen-level metrics:

    <f_n>           = mean normal contact force
    <f_n s>         = mean per-contact normal force in the (z,theta) plane (N)
    Phi_aa          = (1/N_c) sum_c (n_a^c)^2          [count-weighted, sums to 1]
    F_n^{aa}        = (1/sum f_n) sum_c f_n^c (n_a^c)^2 [force-weighted, sums to 1]

The first reproduces the diagonal of the standard count-fabric tensor
(Section 3 "Mechanism of torsion-resisting contact fraction"); the
second is the force-weighted analogue that addresses the "future work"
caveat in that subsection.

Run:  uv run torsion_resisting_force.py
"""
from __future__ import annotations

from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path("/Users/hanyusong/thesis/MicroLiq/torsionSim/cyclic_shear")
OUT_TEX = Path(__file__).resolve().parent / "torsion_resisting_force.tex"
OUT_CSV = Path(__file__).resolve().parent / "torsion_resisting_force.csv"

CASES = [
    (Dr, K0)
    for Dr in (75, 90)
    for K0 in (0.50, 0.67, 1.00, 1.50, 2.00)
]


def case_dir(Dr: int, K0: float) -> Path:
    return ROOT / f"Dr{Dr}" / f"k{K0:.2f}" / "csr_0.300" / "contact_full"


def to_local(n_g: np.ndarray, pos: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    pxy = np.linalg.norm(pos[:, :2], axis=1)
    keep = pxy > 1e-12
    n_g = n_g[keep]; p = pos[keep]; pxy = pxy[keep]
    rx, ry = p[:, 0] / pxy, p[:, 1] / pxy
    tx, ty = -p[:, 1] / pxy, p[:, 0] / pxy
    n_th = n_g[:, 0] * tx + n_g[:, 1] * ty
    n_r  = n_g[:, 0] * rx + n_g[:, 1] * ry
    n_z  = n_g[:, 2]
    return np.column_stack([n_th, n_r, n_z]), keep


def process(Dr: int, K0: float) -> dict:
    csv = case_dir(Dr, K0) / "contact_initial.csv"
    df = pd.read_csv(csv)
    df = df[df["contact_type"] == "bb"].reset_index(drop=True)
    n_g = df[["n_x", "n_y", "n_z"]].to_numpy()
    pos = df[["pos_x", "pos_y", "pos_z"]].to_numpy()
    fn  = df["fn"].to_numpy()
    nl, keep = to_local(n_g, pos); fn = fn[keep]
    n_th, n_r, n_z = nl[:, 0], nl[:, 1], nl[:, 2]
    s = np.sqrt(n_th ** 2 + n_z ** 2)

    # Count-weighted fabric diagonal (Phi_ii); reproduces Section 3 Phi.
    N = len(fn)
    Phi_th = (n_th ** 2).sum() / N
    Phi_r  = (n_r  ** 2).sum() / N
    Phi_z  = (n_z  ** 2).sum() / N

    # Force-weighted fabric diagonal (F_n^{ii}); the new piece.
    sw = fn.sum()
    Fn_th = (fn * n_th ** 2).sum() / sw
    Fn_r  = (fn * n_r  ** 2).sum() / sw
    Fn_z  = (fn * n_z  ** 2).sum() / sw

    return {
        "Dr": Dr, "K0": K0, "N_bb": N,
        "fn_mean": float(fn.mean()),
        "fn_s_mean": float((fn * s).mean()),         # <f_n s>, units N
        "Phi_th": Phi_th, "Phi_r": Phi_r, "Phi_z": Phi_z,
        "Fn_th": Fn_th, "Fn_r": Fn_r, "Fn_z": Fn_z,
    }


def main() -> None:
    rows = [process(Dr, K0) for Dr, K0 in CASES]
    df = pd.DataFrame(rows)
    df["one_minus_Phi_r"] = 1.0 - df["Phi_r"]                # count torsion-resisting fraction
    df["one_minus_Fn_r"] = 1.0 - df["Fn_r"]                  # force torsion-resisting fraction

    # Console report.
    cols = ["Dr", "K0", "N_bb", "fn_mean", "fn_s_mean",
            "Phi_th", "Phi_r", "Phi_z", "one_minus_Phi_r",
            "Fn_th", "Fn_r", "Fn_z", "one_minus_Fn_r"]
    f3 = lambda x: f"{x:.3f}"
    fmt = {k: f3 for k in ("fn_mean", "fn_s_mean",
           "Phi_th", "Phi_r", "Phi_z", "one_minus_Phi_r",
           "Fn_th", "Fn_r", "Fn_z", "one_minus_Fn_r")}
    print(df[cols].to_string(index=False, formatters=fmt))
    df.to_csv(OUT_CSV, index=False)
    print(f"\nWrote {OUT_CSV}")

    # Emit LaTeX macros.  Naming: \<Quantity>Dr<Dr>K<K0_int> where K0_int = round(100*K0).
    def macro_name(prefix: str, Dr: int, K0: float) -> str:
        return f"\\{prefix}Dr{Dr}K{int(round(K0 * 100)):03d}"

    lines = [
        "% Auto-generated by torsion_resisting_force.py — do not edit by hand.",
        "% Initial-state (post-consolidation) cylindrical decomposition for the",
        "% expanded simulation set (2 D_r x 5 K_0, CSR = 0.300).",
        "%",
        "% Macro naming: \\<Q>Dr<Dr>K<K0x100>",
        "%   Q = FnSmean       <f_n s>          per-contact normal force in (z,theta) plane (N)",
        "%   Q = OneMinusPhiR  1 - Phi_rr       count-weighted torsion-resisting fraction",
        "%   Q = OneMinusFnR   1 - F_n^{rr}     force-weighted torsion-resisting fraction",
        "%   Q = FnRR          F_n^{rr}         force-weighted radial share (geometrically inert)",
        "%   Dr in {75, 90};  K0 in {050, 067, 100, 150, 200}",
        "",
    ]
    for r in rows:
        Dr, K0 = r["Dr"], r["K0"]
        lines.append(f"% Dr={Dr}, K0={K0:.2f}, N_bb={r['N_bb']}")
        lines.append(f"\\newcommand{{{macro_name('FnSmean', Dr, K0)[1:]}}}{{{r['fn_s_mean']:.3f}}}")
        lines.append(f"\\newcommand{{{macro_name('OneMinusPhiR', Dr, K0)[1:]}}}{{{1.0 - r['Phi_r']:.3f}}}")
        lines.append(f"\\newcommand{{{macro_name('OneMinusFnR',  Dr, K0)[1:]}}}{{{1.0 - r['Fn_r']:.3f}}}")
        lines.append(f"\\newcommand{{{macro_name('FnRR',         Dr, K0)[1:]}}}{{{r['Fn_r']:.3f}}}")
        lines.append("")
    OUT_TEX.write_text("\n".join(lines))
    print(f"Wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
